### PR TITLE
Removed hard-coded permalinks

### PR DESCRIPTION
**Pull request by briandamaged**
I liked your theme, but my site currently does not contain an "About" page.  So, I borrowed a few snippets from the "Minima" theme to generalize the rendering of the permalinks.

### CODE REVIEW

**Comment by briandamaged** [comment]
FYI: Looks like this logic interferes w/ the pagination gem.  So, I'm still figuring out how to handle that detail properly.

**Comment by briandamaged** [comment]
FYI: The "repeated permalinks" issue appears to be resolved.  But, I had to upgrade the pagination gem to do so.

**Comment by chesterhow** [comment]
@briandamaged Umm, after merging your PR, the posts no longer show up on the github pages site https://chesterhow.github.io/tale/

Could you test it on your fork first and see if you're encountering the same issue? I'll revert the commits for now.. 😅

**Comment by chesterhow** [comment]
screen shot 2018-01-25 at 1 08 18 pm
Screenshot for reference

**Comment by briandamaged** [comment]
Oh -- interesting.  It was working locally, but perhaps I forgot to push the last commit?  I'll try to take a look later today.

**Comment by briandamaged** [comment]
Also: that's the "example" site that was included with the repo, correct?  Or, is this a different site?

(One "gotcha" that currently exists: it appears that the most recent version of the pagination library requires you to explicitly enable pagination on each "hosting" page.  Ex: if your site's homepage contains a pagination component, then it needs to enable pagination in its frontmatter)

**Comment by chesterhow** [comment]
It worked locally for me too when I tried debugging it 🤔

Yup that’s the example site which is built with the code in this repository itself.

Can’t seem to figure out why the posts dont work. Could you try enabling github pages on your fork? Perhaps we could try debugging from there :)

**Pull request merged**
