### PR TITLE
Change default sans serif font on windows

### PR DESCRIPTION
**Pull request by chesterhow**
Switched to Segoe UI instead of Arial

### CODE REVIEW

**Comment by vmavromatis** [comment]
I think the font change broke the theme :(

**Comment by chesterhow** [comment]
@vmavromatis yea it messed up mine too. Don't worry I'm fixing it now :)

**Comment by chesterhow** [comment]
@vmavromatis It's fixed now :D

**Comment by vmavromatis** [comment]
All good. Thanks!

**Pull request merged**
