### PR TITLE
add stickie(pinned) and customized subtitles

### PR DESCRIPTION
**Pull request by AzulRadio**
Hi! I really love Tale's artstyle! Thank you for your contribution!

When I build my blog with Tale, I noticed that Tale doesn't have the functionality to pin a post. I also noticed that I can't customize the post subtitle on the homepage. So I changed home.html to add these two functionalities.

To use them, do as follows in the post header: 

title = "This is the title"
subtitle = "a subtitle"
stickie = true /* if true pin the post, pinned posts ranked in time order */

If you don't add these two variables, Tale will act just as before my changes.

NOTE: I know nothing about the front-end programming or web dev and googled my way through all these. So if there's anything wrong feel free to let me know.
Thanks again for your awesome theme!

### CODE REVIEW

**Comment by Mo9a7i** [comment]
I like the pinning feature. Not sure what you mean by subtitle, is it the body text of the post that gets truncated ?

**Comment by AzulRadio** [comment]
> I like the pinning feature. Not sure what you mean by subtitle, is it the body text of the post that gets truncated ?

Yes.

On the homepage, every article has an abstract under its title that is, by default, a 30-word truncation. This truncation splits sentence with blank and works poorly for languages that don't separate words with blanks, i.e. most languages in Asia. 

The "subtitle" fixes that. When you have a "subtitle = " in the post header, the abstract on the homepage for the article will be replaced by your "subtitle". 

I just realized "subtitle" may not be the perfect word to describe it. I'm trying to say the smaller title under a big title (usually seen in newspapers). Feel free to help me pick a better word.

**Comment by chesterhow** [comment]
Hi @AzulRadio thank you for the contribution! 👍  And apologies for the late response...

Regarding the subtitle request, I've addressed it in my latest PR #98, which allows you to customise excerpts.

As for the stickied post feature, let me double-check your implementation and get back to you!

**Comment by chesterhow** [comment]
@AzulRadio I've reviewed your sticky post implementation and I'm afraid there are some limitations to it.

Primarily, because you are using `paginator` to search for stick posts, therefore only sticky posts from that page will be pinned to the top. For example, if I have 2 pages of posts, and I've stickied a post from the second page, the sticky post will not show up on the first page.

I've implemented the sticky post feature in my latest PR #99. Nonetheless thank you for taking the time to contribute and suggest new features! Hope the new sticky feature works for you 😄

**Pull request closed without merging**
